trigger:
- master
- release 

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.24'

# MASTER BRANCH ONLY
- script: dotnet pack --configuration $(buildConfiguration) --version-suffix "build-$(Build.BuildNumber)" -o "$(Build.ArtifactStagingDirectory)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'dotnet pack $(buildConfiguration)'

# RELEASE BRANCH
- script: dotnet pack --configuration $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  displayName: 'dotnet pack $(buildConfiguration)'

#PUBLISH ARTIFACTS 
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
  displayName: 'Publish Artifacts'


#- task: Bash@3
#  inputs:
#    targetType: inline
#    script: |
#      # The reason this has to be done - https://github.com/NuGet/Home/issues/8022
#      # rename npm package reference in adal-node
#      # covers package.json and any file referencing package
#      find ./node_modules/adal-node -type f -exec sed -i -e 's/xpath.js/xpathjs/g' {} \;

#      # rename the xpath.js npm package folder and name
#      mv ./node_modules/xpath.js ./node_modules/xpathjs

#      # change the name in the package.json to reflect naming change
#      find ./node_modules/xpathjs -type f -exec sed -i -e 's/xpath.js/xpathjs/g' {} \;
#  displayName: 'fixup for NuGet Pack Issue'

#- script : dotnet pack azure.csproj --no-build --configuration $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)"
#  displayName: 'Run .NET Pack'

